---
# deploy code and restart services

- hosts: all
  gather_facts: false
  become: yes
  become_method: sudo
  roles:
    - deploy
  vars_prompt:
    - name: commit
      prompt: git branch to deploy
      default: master
      private: no
