---
# provision machine and deploy code

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - base
    - configure
    - nginx
    - services
    - { role: development, when: "env == 'development'" }
