---
- name: apt-cache is updated
  apt: update_cache=yes

- name: nginx is installed
  apt: name=nginx state=present

- name : node ppa key is added
  apt_key: url='https://deb.nodesource.com/gpgkey/nodesource.gpg.key' state=present

- name: node ppa is available
  apt_repository: repo='deb https://deb.nodesource.com/node_0.12 trusty main' update_cache=yes

- name: git is installed
  apt: name=git state=present

- name: apt cache is updated
  apt: update_cache=yes

- name: nodejs is installed
  apt: name=nodejs state=latest
