---
- name: code is synchronized via git to temp directory
  git: dest={{app_base_path}}.tmp repo={{git_repo}} version={{commit}}
  when: env != 'development'

- name: npm install has been run
  npm: path={{app_base_path}}.tmp

- name: production version of the application has been built
  command: npm run build
  args:
    chdir: "{{ app_base_path }}.tmp"

- name: log file exists
  file: path={{log_file}} state=touch owner={{app_user}} group={{app_group}}

- name: current production build is removed
  command: rm -rf {{app_base_path}}

- name: new production build is in place
  command: mv {{app_base_path}}.tmp {{app_base_path}}

- name: the service is restarted
  service: name=weekly-review state=restarted
