---
# configure for production

- name: Make sure the base directory exsists
  file: path={{app_base_path}}src state=directory

- name: Build the production version of the application
  command: npm run build
  args:
    creates: "{{ app_base_path }}app-production.js"
    chdir: "{{ app_base_path }}"

- name: Make sure the optimized front end JavaScript is on the box
  synchronize: src=../../app-production.js dest={{app_base_path}}

- name: Make sure the front end assets are on the box
  synchronize: src=../../src/client dest={{app_base_path}}src

- name: Make sure the server code is on the box
  synchronize: src=../../src/server dest={{app_base_path}}src

# this will go away as soon as auth is moved to api.bocoup.com
- name: Make sure node_modules are on the box
  synchronize: src=../../node_modules dest={{app_base_path}}

- name: Make sure a project config directory exists
  file: path={{app_base_path}}/config state=directory

- name: Make sure the github auth config file is on the box
  synchronize: src=../../config/secrets/github.json dest={{app_base_path}}config/secrets/
